### ISSUE TITLE
Setup a GitHub workflow for Continuous Integration

### ISSUE THREAD

**Issue by mitchmindtree** [Mutualideas/lyfcal#3]
GitHub allows for setting up automated "workflows" under certain conditions (e.g. when you push code to master, or when you open a Pull Request). It's an awesome way of ensuring that everything is always building successfully, tests are passing, code is formatted correctly, linter suggestions are applied, etc.

GitHub workflows are declared within a `.github/workflows` directory in your repo, e.g. `.github/workflow/ci.yml` for your "continuous integration" workflow.

> *Note: `.yml` files (or YAML files) are just another configuration file format, similar to `.toml` but a bit more flexible.*

I'd recommend setting up a workflow under this repo that has jobs for the following:

- `cargo test --locked` - this ensures everything compiles and that any tests (if you have them now or add them in the future) pass successfully. The `--locked` flag ensures that the `Cargo.lock` file that is included in the repo is up to date.
- `cargo fmt --check` - this ensures that all code is formatted to the default formatting standard.
- `cargo clippy -- -D warnings` - this runs [the `clippy` linter](https://doc.rust-lang.org/clippy/usage.html) to check for anti-patterns and for opportunities to change parts of code to be more conventional. The `-D warnings` flag causes it to actually produce errors in the case that any lints have not been addressed.

## Example CI workflow

Here's a simplified workflow similar to what I use for personal projects:

```yml
name: ci

# Trigger the workflow when pushing to `main` or when a pull request is opened.
on:
  push:
    branches:
      - main
  pull_request:

# Declare all the jobs here.
jobs:
  # Here we declare one "cargo" job, but with a matrix providing different cargo
  # commands we want to run. We can split the different commands into their own
  # jobs, but it can be a little more concise to declare them like this.
  cargo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: clippy -- -D warnings
          - command: fmt -- --check
          - command: test --locked
    steps:
    # This action allows the workflow to checkout the repo.
    - uses: actions/checkout@v3
    # This action provides the Rust toolchain (cargo, clippy, rustfmt, etc).
    - uses: actions-rs/toolchain@v1
    # This action sets up a cache for the Rust build artifacts.
    - uses: Swatinem/rust-cache@v2
    # Here we run the command.
    # This whole job will get run once for each command in the matrix above.
    - run: cargo ${{ matrix.command }}
```

---

Feel free to lookup "Rust GitHub Workflows" as many people have different opinions and tips on how to set them up.
